apiVersion: 1

groups:
  - name: Cache Alerts
    folder: Cache Monitoring
    interval: 1m
    rules:
      - title: High Cache Miss Rate
        condition: B
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: 'rate(cache_misses_total{cache="userCache"}[5m]) / (rate(cache_hits_total{cache="userCache"}[5m]) + rate(cache_misses_total{cache="userCache"}[5m]))'
              intervalMs: 1000
              maxDataPoints: 43200
          - refId: B
            datasourceUid: prometheus
            model:
              conditions:
                - evaluator:
                    params:
                      - 0.3
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    type: avg
                  type: query
              expr: ''
        noDataState: OK
        execErrState: Alerting
        for: 5m
        annotations:
          description: 'Cache miss rate is above 30% for 5 minutes'
          summary: 'High cache miss rate detected'
        labels:
          severity: warning
          
      - title: High Cache Latency
        condition: B
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: 'histogram_quantile(0.95, rate(cache_operation_duration_seconds_bucket{operation="get"}[5m]))'
              intervalMs: 1000
              maxDataPoints: 43200
          - refId: B
            datasourceUid: prometheus
            model:
              conditions:
                - evaluator:
                    params:
                      - 0.1
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    type: avg
                  type: query
              expr: ''
        noDataState: OK
        execErrState: Alerting
        for: 5m
        annotations:
          description: '95th percentile cache latency is above 100ms for 5 minutes'
          summary: 'High cache latency detected'
        labels:
          severity: warning
